config/routes.rb
Rails.application.routes.draw do
  resources :movies, only: [:index, :new, :create]
  resources :series, only: [:index, :new, :create]
  resources :documentary_films, only: [:index, :new, :create]

  # Ruta para verificar el estado de salud de la aplicación
  get "up" => "rails/health#show", as: :rails_health_check

  # Puedes definir una ruta raíz si es necesario
  # root "movies#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentary_film.rb
class DocumentaryFilm < ApplicationRecord
  validates :name, :synopsis, :director, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :name, :synopsis, :director, presence: true
end

app/models/serie.rb
class Serie < ApplicationRecord
  validates :name, :synopsis, :director, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documentary_films_controller.rb
class DocumentaryFilmsController < ApplicationController
  def index
    @documentary_films = DocumentaryFilm.all
  end

  def new
    @documentary_film = DocumentaryFilm.new
  end

  def create
    @documentary_film = DocumentaryFilm.new(documentary_film_params)
    if @documentary_film.save
      redirect_to documentary_films_path
    else
      render :new
    end
  end

  private

  def documentary_film_params
    params.require(:documentary_film).permit(:name, :synopsis, :director)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path
    else
      render :new
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:name, :synopsis, :director)
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def index
    @series = Serie.all
  end

  def new
    @serie = Serie.new
  end

  def create
    @serie = Serie.new(serie_params)
    if @serie.save
      redirect_to series_path
    else
      render :new
    end
  end

  private

  def serie_params
    params.require(:serie).permit(:name, :synopsis, :director)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentary_films_helper.rb
module DocumentaryFilmsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/documentary_films/create.html.erb
<h1>DocumentaryFilms#create</h1>
<p>Find me in app/views/documentary_films/create.html.erb</p>

app/views/documentary_films/index.html.erb
<h1>Documentaries</h1>
<%= link_to 'Add Documentary', new_documentary_film_path %>
<ul>
  <% @documentary_films.each do |documentary_film| %>
    <li><strong><%= documentary_film.name %></strong> - <%= documentary_film.director %></li>
  <% end %>
</ul>

app/views/documentary_films/new.html.erb
<h1>Add a New Documentary</h1>
<%= form_with model: @documentary_film, local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :synopsis %>
    <%= form.text_area :synopsis %>
  </div>
  <div>
    <%= form.label :director %>
    <%= form.text_field :director %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioAlmacenarHernan006</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/create.html.erb
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/index.html.erb
<h1>Movies</h1>
<%= link_to 'Add Movie', new_movie_path %>
<ul>
  <% @movies.each do |movie| %>
    <li><strong><%= movie.name %></strong> - <%= movie.director %></li>
  <% end %>
</ul>

app/views/movies/new.html.erb
<h1>Add a New Movie</h1>
<%= form_with model: @movie, local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :synopsis %>
    <%= form.text_area :synopsis %>
  </div>
  <div>
    <%= form.label :director %>
    <%= form.text_field :director %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/series/create.html.erb
<h1>Series#create</h1>
<p>Find me in app/views/series/create.html.erb</p>

app/views/series/index.html.erb
<h1>Series</h1>
<%= link_to 'Add Series', new_series_path %>
<ul>
  <% @series.each do |serie| %>
    <li><strong><%= serie.name %></strong> - <%= serie.director %></li>
  <% end %>
</ul>

app/views/series/new.html.erb
<h1>Add a New Series</h1>
<%= form_with model: @serie, local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :synopsis %>
    <%= form.text_area :synopsis %>
  </div>
  <div>
    <%= form.label :director %>
    <%= form.text_field :director %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>